[package]
name = "ckb-indexer"
version = "0.40.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "CKB internal indexer. This is deprecated. Please use https://github.com/nervosnetwork/ckb-indexer"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = { path = "../util/types", version = "= 0.40.0-pre" }
ckb-db = { path = "../db", version = "= 0.40.0-pre" }
ckb-shared = { path = "../shared", version = "= 0.40.0-pre" }
ckb-store = { path = "../store", version = "= 0.40.0-pre" }
ckb-jsonrpc-types = { path = "../util/jsonrpc-types", version = "= 0.40.0-pre" }
ckb-logger = { path = "../util/logger", version = "= 0.40.0-pre" }
ckb-util = { path = "../util", version = "= 0.40.0-pre" }
ckb-app-config = { path = "../util/app-config", version = "= 0.40.0-pre" }
ckb-db-migration = { path = "../db-migration", version = "= 0.40.0-pre" }
ckb-db-schema = { path = "../db-schema", version = "= 0.40.0-pre" }

[dev-dependencies]
tempfile = "3.0"
ckb-chain =  { path = "../chain", version = "= 0.40.0-pre" }
ckb-chain-spec = { path = "../spec", version = "= 0.40.0-pre" }
ckb-resource = { path = "../resource", version = "= 0.40.0-pre" }
