[package]
name = "ckb-multisig"
version = "0.40.0-pre"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
description = "CKB multi-signature library."
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-error = { path = "../../error", version = "= 0.40.0-pre" }
ckb-logger = { path = "../logger", version = "= 0.40.0-pre" }
ckb-crypto = { path = "../crypto", version = "= 0.40.0-pre" }

[dev-dependencies]
rand = "0.7"
